language: rust
rust: nightly

matrix:
  fast_finish: true
  include:
    - name: "miri"
      env: TARGET=x86_64-unknown-linux-gnu
      script: sh ci/miri.sh
    - name: "rustfmt/clippy"
      env: TARGET=i586-unknown-linux-gnu
      script: sh ci/tools.sh
    - name: "docs"
      env: TARGET=x86_64-unknown-linux-gnu
      script:
        - cargo -vv doc --features nightly,serde,rayon
        - echo '<meta http-equiv=refresh content=0;url=hashbrown/index.html>' > target/doc/index.html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: target/doc
        keep-history: false
        on:
          branch: master

    # Tier 1 targets:
    - name: "x86_64-unknown-linux-gnu"
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (beta)"
      rust: beta
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (stable)"
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "x86_64-unknown-linux-gnu (Rust 1.31.0)"
      rust: 1.31.0
      env: TARGET=x86_64-unknown-linux-gnu
    - name: "i686-unknown-linux-gnu"
      env: TARGET=i686-unknown-linux-gnu CROSS=1
    - name: "x86_64-apple-darwin"
      env: TARGET=x86_64-apple-darwin
      os: osx
      osx_image: xcode10
    - name: "i686-apple-darwin"
      env: TARGET=i686-apple-darwin
      os: osx
      osx_image: xcode10
    - name: "x86_64-pc-windows-msvc"
      env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - name: "x86_64-pc-windows-gnu"
      env: TARGET=x86_64-pc-windows-gnu CROSS=1
    - name: "i686-pc-windows-gnu"
      env: TARGET=i686-pc-windows-gnu CROSS=1

    # Tier 2/3 targets:
    - name: "i586-unknown-linux-gnu (no SSE2)"
      env: TARGET=i586-unknown-linux-gnu CROSS=1
    - name: "armv7-unknown-linux-gnueabihf"
      env: TARGET=armv7-unknown-linux-gnueabihf CROSS=1
    - name: "aarch64-unknown-linux-gnu"
      env: TARGET=aarch64-unknown-linux-gnu CROSS=1

install: travis_retry rustup target add "${TARGET}"
script: sh ci/run.sh

branches:
  # Don't build these branches
  except:
    # Used by bors
    - trying.tmp
    - staging.tmp
